"""What every air-quality ingester does with what it fetched.

Three feeds now write to `air_quality_events` — CPCB through data.gov.in, the
same stations through WAQI, and CAMS through Open-Meteo. They differ entirely in
how they obtain a reading and not at all in what happens next, so the part that
touches the database lives here once. Triplicating it is how one of the three
ends up quietly not flipping its source to ACTIVE, or writing rows nobody
overlays onto the curated layer.

Nothing here decides provenance. That is a property of the source, recorded in
`data_sources.provenance` by migration V19, and an ingester that could choose it
per run could label a model's output as an instrument's.
"""

from __future__ import annotations

import json
import math
import uuid
from dataclasses import dataclass
from datetime import datetime

import psycopg
from psycopg.rows import tuple_row

from common.db import execute_batched


@dataclass(frozen=True)
class Zone:
    id: int
    code: str
    latitude: float
    longitude: float


@dataclass(frozen=True)
class Reading:
    """One AQI for one zone at one moment, with whatever concentrations were
    behind it.

    Concentrations are optional and stay optional. A feed that publishes an
    index without them writes the index alone; filling the columns with values
    reconstructed for the sake of having them would put numbers in the database
    that no instrument reported.
    """

    zone_id: int
    event_time: datetime
    aqi: int
    category: str
    pm25: float | None = None
    pm10: float | None = None
    no2: float | None = None
    o3: float | None = None
    co: float | None = None


def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance. Straight-line degrees are not distance in India."""
    radius = 6371.0
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2
         + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) ** 2)
    return 2 * radius * math.asin(math.sqrt(a))


def source_id(connection: psycopg.Connection, code: str) -> int | None:
    with connection.cursor(row_factory=tuple_row) as cursor:
        cursor.execute("SELECT id FROM data_sources WHERE code = %s", (code,))
        row = cursor.fetchone()
    return None if row is None else int(row[0])


def active_zones(connection: psycopg.Connection) -> list[Zone]:
    # Read with its own row factory rather than the caller's. Positional
    # unpacking against a dict row silently iterates its keys, which is how an
    # earlier version of this query produced "could not convert string to
    # float: 'occupancy_ratio'" instead of a number.
    with connection.cursor(row_factory=tuple_row) as cursor:
        cursor.execute("""
            SELECT id, code, center_latitude, center_longitude
              FROM zones
             WHERE active AND deleted_at IS NULL
             ORDER BY code
        """)
        return [Zone(int(i), str(code), float(lat), float(lon))
                for i, code, lat, lon in cursor.fetchall()]


def nearest_zone(zones: list[Zone], latitude: float, longitude: float,
                 max_km: float) -> tuple[Zone, float] | None:
    """The zone a fixed instrument can be said to measure, or nothing.

    Beyond `max_km` the answer is nothing rather than the closest candidate.
    Air quality varies over kilometres, so attributing a station to whatever
    happened to be least far away is how a monitored junction's reading ends up
    published as a suburb's.
    """
    best: tuple[Zone, float] | None = None
    for zone in zones:
        km = haversine_km(latitude, longitude, zone.latitude, zone.longitude)
        if km <= max_km and (best is None or km < best[1]):
            best = (zone, km)
    return best


def write(connection: psycopg.Connection, source: int, readings: list[Reading]) -> int:
    """Insert readings and return how many rows were offered.

    `demo_data` is FALSE on every row this writes. It means "not generated by
    this platform", which is true of a model's output as much as an
    instrument's; the finer question of which is answered by the source's
    provenance.
    """
    if not readings:
        return 0

    rows = [(
        str(uuid.uuid4()), r.zone_id, source, r.event_time, r.aqi, r.category,
        r.pm25, r.pm10, r.no2, r.o3, r.co, False,
    ) for r in readings]

    execute_batched(connection, """
        INSERT INTO air_quality_events
            (event_id, zone_id, source_id, event_time, aqi, category,
             pm25, pm10, no2, o3, co, demo_data)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (event_id) DO NOTHING
    """, rows)
    return len(rows)


def mark_delivered(connection: psycopg.Connection, source: int,
                   attribution: list[dict] | None = None) -> None:
    """Record that this feed delivered, and who it must be credited to.

    Activated here rather than by a migration. V16 and V19 seed these sources
    PAUSED because a source marked ACTIVE while nothing feeds it appears on the
    Data Health page as a silent feed — a fault report for a deliberate state. A
    delivery is the evidence that the feed works, and it is evidence this
    deployment produced rather than one the repository asserted on behalf of
    every fork.

    `attribution` is written from what the provider returned about the readings
    now held, not from a constant. WAQI's terms require crediting the
    originating agency, which differs per station, so the only correct list is
    the one derived from the response.
    """
    with connection.cursor() as cursor:
        if attribution is None:
            cursor.execute(
                "UPDATE data_sources SET last_ingested_at = now(), status = 'ACTIVE' "
                "WHERE id = %s", (source,))
        else:
            cursor.execute(
                "UPDATE data_sources SET last_ingested_at = now(), status = 'ACTIVE', "
                "attribution = %s::jsonb WHERE id = %s",
                (json.dumps(attribution), source))
    connection.commit()
