-- =============================================================================
-- V16 — CPCB as a real data source (PRD §19, §43)
--
-- The first source in the platform that is not synthetic. Every other feed is
-- generated by design so the product runs with no external dependency; this one
-- reads the Central Pollution Control Board's national air quality feed through
-- data.gov.in.
--
-- demo_data = FALSE, and that flag is the entire reason the row differs from the
-- five above it. Readings loaded through this source carry FALSE too, so the
-- dashboard can distinguish a measured AQI from a generated one — per reading,
-- not per city. A city with real air quality and synthetic traffic is exactly
-- that, and the flags say so at the level where it is true.
--
-- Seeded as PAUSED. Ingestion needs an API key that is not in this repository
-- and never will be, and a source marked ACTIVE while nothing feeds it would
-- appear on the Data Health page as a silent feed — a fault report for a
-- deliberate state. It becomes ACTIVE when someone configures a key.
-- =============================================================================

INSERT INTO data_sources (uid, code, name, description, source_type,
                          ingestion_mode, status, config, demo_data) VALUES
    (gen_random_uuid(),
     'cpcb-air-quality',
     'CPCB National Air Quality',
     'Central Pollution Control Board station readings via data.gov.in. Real '
     || 'measurements: the AQI is computed from reported pollutant concentrations '
     || 'using CPCB''s own sub-index breakpoints, and a station is only attributed '
     || 'to a zone it is within 8 km of.',
     'AIR_QUALITY',
     'REST_API',
     'PAUSED',
     -- Non-secret shaping only. The API key comes from the environment; nothing
     -- in this column may be sensitive (PRD §30).
     '{"resourceId": "3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69", "maxStationKm": 8.0, "provider": "data.gov.in"}'::jsonb,
     FALSE);
