import type { AirProvenance } from "@/lib/api/types";

/**
 * How the three provenances are named and explained on screen.
 *
 * Centralised because the words are the product. A reader glancing at an AQI
 * has to be able to tell, in one token, whether an instrument reported it, a
 * model of the real atmosphere produced it, or this platform invented it — and
 * if two screens use different words for the same state, that distinction stops
 * being legible.
 *
 * "modelled" rather than "estimated" or "approximate": those describe a
 * confidence, and the point here is a kind. CAMS output is not a worse
 * measurement, it is a different sort of claim about the same air.
 */
export const PROVENANCE_LABEL: Record<AirProvenance, string> = {
  MEASURED: "measured",
  MODELLED: "modelled",
  SYNTHETIC: "synthetic",
};

export const PROVENANCE_DETAIL: Record<AirProvenance, string> = {
  MEASURED: "Reported by a government monitoring station within 8 km of this zone.",
  MODELLED:
    "From Copernicus CAMS, a physical model of the real atmosphere. Real conditions, " +
    "but no instrument measured this zone.",
  SYNTHETIC: "Generated by this platform. No external feed covers this zone and hour.",
};

/**
 * The badge tone for a provenance.
 *
 * Synthetic is the only one marked, and it is marked as a caution rather than a
 * fault: the generated feeds are the platform's design, not a failure. Measured
 * and modelled are both real, so neither is coloured — a reader should not have
 * to decode a palette to find the one number that was invented.
 */
export function provenanceLevel(source: AirProvenance): "neutral" | "moderate" {
  return source === "SYNTHETIC" ? "moderate" : "neutral";
}

/** `"192 (MODERATE) · modelled"`, or a plain dash when there is no reading. */
export function describeAqi(
  aqi: number | null,
  category: string | null,
  source: AirProvenance | null,
): string {
  if (aqi === null) return "Not measured";
  const provenance = source ? ` · ${PROVENANCE_LABEL[source]}` : "";
  return `${aqi} (${category ?? "—"})${provenance}`;
}
