import type { AirProvenance } from "@/lib/api/types";

/**
 * How the three provenances are named on screen, and what they mean underneath.
 *
 * Centralised because the words are the product. A reader glancing at an AQI has
 * to be able to tell whether an instrument reported it, a model of the real
 * atmosphere produced it, or this platform invented it — and if two screens use
 * different words for the same state, that distinction stops being legible.
 *
 * **Two registers, not one.** The screen says "from a sensor"; the tooltip says
 * MEASURED and defines it. That is not the precision being softened — it is the
 * precision being put where it can be read. "Modelled" is a term of art: it
 * means a different *kind* of claim, not a worse measurement, and a reader who
 * does not already know that reads it as "guessed" and discounts a real number.
 * The plain phrase carries the meaning; the exact term stays one hover away for
 * anyone who needs to cite it.
 *
 * The exact words are unchanged from what the API returns, so nothing here
 * invents a vocabulary the backend does not have.
 */

/** What the reader sees. Says the kind of thing, in words needing no glossary. */
export const PROVENANCE_LABEL: Record<AirProvenance, string> = {
  MEASURED: "from a sensor",
  MODELLED: "from a forecast model",
  SYNTHETIC: "demo data",
};

/**
 * The compact form, for a table cell with sixty-two rows in it.
 *
 * Words, not initials. This was `PROVENANCE_LABEL[source].charAt(0)`, which
 * rendered MEASURED and MODELLED identically — both "m" — so the one column
 * built to separate an instrument from a model could not, and the two states
 * this platform works hardest to distinguish looked the same wherever it
 * mattered most.
 */
export const PROVENANCE_MARK: Record<AirProvenance, string> = {
  MEASURED: "sensor",
  MODELLED: "model",
  SYNTHETIC: "demo",
};

/** The exact term the API uses, for anyone who needs to cite or search it. */
export const PROVENANCE_EXACT: Record<AirProvenance, string> = {
  MEASURED: "MEASURED",
  MODELLED: "MODELLED",
  SYNTHETIC: "SYNTHETIC",
};

export const PROVENANCE_DETAIL: Record<AirProvenance, string> = {
  MEASURED: "Reported by a government monitoring station within 8 km of this zone.",
  MODELLED:
    "From a physical model of the real atmosphere — Copernicus CAMS for air, the " +
    "Open-Meteo forecast for weather. Real conditions, but no instrument stood here.",
  SYNTHETIC: "Generated by this platform. No real feed covers this zone and hour.",
};

/**
 * The hover text: the exact term first, then what it means.
 *
 * Both halves matter. The term is what appears in the API, the database and the
 * documentation, so a reader who wants to look it up needs to see it spelled the
 * way it is spelled there; the sentence is what makes it mean something to
 * everyone else.
 */
export function provenanceTooltip(source: AirProvenance): string {
  return `${PROVENANCE_EXACT[source]} — ${PROVENANCE_DETAIL[source]}`;
}

/**
 * The badge tone for a provenance.
 *
 * Demo data is the only one marked, and it is marked as a caution rather than a
 * fault: the generated feeds are the platform's design, not a failure. A sensor
 * reading and a model's are both real, so neither is coloured — a reader should
 * not have to decode a palette to find the one number that was invented.
 */
export function provenanceLevel(source: AirProvenance): "neutral" | "moderate" {
  return source === "SYNTHETIC" ? "moderate" : "neutral";
}

/** `"192 (Unhealthy) · from a forecast model"`, or a plain phrase when there is none. */
export function describeAqi(
  aqi: number | null,
  category: string | null,
  source: AirProvenance | null,
): string {
  if (aqi === null) return "No reading";
  const provenance = source ? ` · ${PROVENANCE_LABEL[source]}` : "";
  return `${aqi} (${category ?? "—"})${provenance}`;
}
